### ISSUE TITLE
use the attribute with user get error for htmlentities() 

### ISSUE THREAD

**Issue by tkart38** [Remo/concrete5-attribute-multi-text#1]
hi 
i've set the attribute type  to the user
 if i set an attribute value the dashboard user search (/dashboard/users/search/view/54) get this error:

htmlentities() expects parameter 1 to be string, array given

is possible to use this attribute for the users?

**Comment by Remo** [comment]
currently not because the search form isn't implemented

**Comment by tkart38** [comment]
thanks
i've solved using your "attribute-free-form" package this work fine for me.

thanks again
