### ISSUE TITLE
doesn't work on user?

### ISSUE THREAD

**Issue by tkart38** [Remo/concrete5-attribute-multi-text#2]
hi ,
i'm trying to use this attribute type for user but get an error :

/concrete\/src\/Utility\/Service\/Text.php","line":136,"function":null,"class":"Whoops\\Exception\\ErrorException","args":["htmlentities() expects parameter 1 to be string, array given"]},{"file":null,"line":null,"function":"handleError","class":"Whoops\\Run","args":[2,"htmlentities() expects parameter 1 to be string, array 

Is possible to use it as user attribute?
thanks in advances
bye

**Comment by Remo** [comment]
I don't see why it shouldn't work as a user attribute, but I can't help you unless I can reproduce the problem. Can you guide me through the steps to get the same error?

**Comment by tkart38** [comment]
hi 
i'm using concrete 	5.7.5.6 and i've installed the package.
I've set the attribute type for user in system-setting - attribute- type.
After i've add an attribute on the user attributes panel.
When i set the first attribute from the dasboard user page (/index.php/dashboard/users/search/view/234) i get the error.
After when you return on the user page with the attribute setted get the error again it seems that the getvalue can't get the value for the form. 
thanks

**Comment by Remo** [comment]
I've tested this on 5.7.5.8, the oldest version I'm still running and it works just fine.
![image](https://user-images.githubusercontent.com/129864/27473281-e03125ca-57fe-11e7-8d6c-c997031f968a.png)

Have you tried this on a clean installation? Maybe there's something in your site or maybe try to upgrade to a newever version, yours is pretty old, even 5.7 is at 5.7.5.13

**Comment by tkart38** [comment]
hi,
i've tested in 5.7.5.8 /9 and 13 clean installation.

and give the same error
![cattura](https://user-images.githubusercontent.com/16717223/27478159-f523c374-580e-11e7-8eee-f7175acd6b9a.PNG)

this is so strange, there is onlie one different from your and is the language but i've try with the english but the problem persist.

**Comment by Remo** [comment]
can you please update the code and try again?

**Comment by tkart38** [comment]
Now work great!
thanks for you help and nice work!

**Comment by tkart38** [comment]
hi 
just a little question, is possible to update onlie one field of the attribute?
The setattribute() replace the entire array of value.
thanks in advances

**Comment by Remo** [comment]
get the existing array, update the item you want to change and save the whole array again. No support for this out of the box, but it's a one-liner.
